steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - "docker login --username=jeremyadamsfisher1123 --password=$$PASSWORD"
    secretEnv: ["PASSWORD"]

  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "jeremyadamsfisher1123/shakespeare-gpt:0.0.33", "."]

  # Push Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "jeremyadamsfisher1123/shakespeare-gpt:0.0.33"]

availableSecrets:
  secretManager:
    - versionName: projects/deep-learning-404617/secrets/gcloud-dockerhub-login/versions/1
      env: "PASSWORD"
