defaults:
  - base
  
# baby gpt https://github.com/karpathy/nanoGPT/blob/master/config/train_shakespeare_char.py
batch_size: 64
block_size: 256
learning_rate: 0.001
n_embed: 384
n_heads: 6
n_layers: 6
p_dropout: 0.2
n_epochs: 1
tokenizer: null
vocab_size: 75