name: Push to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Cog
        uses: replicate/setup-cog@v1

      - name: Push to DockerHub
        run: |
          # cog push "jeremyadamsfisher1123/shakespeare-gpt:${{  github.ref_name }}"
          cog build -t temp