name: Push to DockerHub

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Dockerhub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username jeremyadamsfisher1123 --password-stdin

      - name: Setup Cog
        run: |
          curl -o /usr/local/bin/cog -L "https://github.com/replicate/cog/releases/latest/download/cog_$(uname -s)_$(uname -m)"
          chmod +x /usr/local/bin/cog

      - name: Push to DockerHub
        run: |
          cog push "jeremyadamsfisher1123/shakespeare-gpt:${{  github.ref_name }}"